#%RAML 1.0
title: calsi-api
version: v0
resourceTypes:
  resourceType:
    get:
      is:
        - que
protocols: [HTTPS,HTTP]
traits:
   que: !include /traits/trait.raml
mediaType: application/json

/addition:
  get:
    is: [que]    
    responses:
      200: 
       body:
        example: !include /examples/addition responses.json
                 
/subtraction:
  get:
    is: [que]    
    responses:
      200: 
       body:
          example: !include /examples/subtraction responses.json 
                 
/division:
  get:
    is: [que]    
    responses:
      200: 
       body:
         example: !include /examples/division responses.json
  
/multiplication :
   get:
    is: [que]    
    responses:
      200: 
       body:
         example: !include /examples/multiplication responses.json